### ISSUE TITLE
docker: SSTATE_MIRROR is not set for non-CI builders

### ISSUE THREAD

**Issue by mythi** [ostroproject/ostro-os-xt#32]
If `docker/local-build.sh` is used outside CI environment, `SSTATE_MIRROR` is not set in `auto.conf`. This increases build times.

**Comment by mythi** [comment]
@okartau As far as I can see ostroproject/ostro-os-xt/blob/master/docker/build-project.sh#L84 branch is taken for all non-CI users. 

We should ensure also SSTATE_MIRROR is set. 

Similar to:

```
echo "SSTATE_MIRRORS ?= \"file://.* ${COORD_BASE_URL}/bb-cache/sstate/PATH\"" >> conf/auto.conf
```

but with `https://download.ostroproject.org/sstate/ostro-os-xt/`

@kad

**Comment by kad** [comment]
This line just overwrites default value with local copy. Defaults are configured in https://github.com/ostroproject/ostro-os-xt/blob/master/meta-ostro-xt/conf/local.conf.sample#L247

**Comment by mythi** [comment]
False report. Sorry.
