### ISSUE TITLE
Socket file descriptors can't be passed to an unprivileged process with unix domain socket

### ISSUE THREAD

**Issue by hujiajie** [ostroproject/ostro-os-xt#43]
**Description**
Socket file descriptors can't be passed to an unprivileged process with unix domain socket when SMACK is enabled.

**Steps to reproduce**
1. Build the test program below
2. Create an unpriviledged user in Ostro OS XT
3. Run the test program as the unpriviledged user

**Expected result**
Parent process sent 5 fds.
Child process received 5 fds.

**Actual result**
Parent process sent 5 fds.
Child process received 0 fds.

After some investigation, I found that it's caused by a kernel bug and it's been fixed by http://git.yoctoproject.org/cgit/cgit.cgi/linux-yocto-4.6/commit/security/smack/smack_lsm.c?h=standard/intel/base&id=79be093500791cc25cc31bcaec5a4db62e21497b. Can you help to backport the patch to Ostro OS XT? Otherwise I have to run such kind of applications as root so that it could run with the `CAP_MAC_OVERRIDE` capability, which is really undesired for security reasons.

```
// test.c
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <unistd.h>

#define NUM_FD 5

int main()
{
  int fds[2];
  struct msghdr msg = {0};
  char dummy[1] = {0};
  struct iovec iov;
  struct cmsghdr *cmsg;
  int myfds[NUM_FD];
  char buf[CMSG_SPACE(sizeof myfds)];
  int *fdptr;
  int i;
  int ret;

  ret = socketpair(AF_UNIX, SOCK_STREAM, 0, fds);
  assert(ret == 0);
  pid_t pid = fork();
  assert(pid != -1);
  if (pid == 0) {
    // child process
    close(fds[0]);
    for (i = 0; i < NUM_FD; i++) {
      myfds[i] = -1;
    }
    iov.iov_base = dummy;
    iov.iov_len = sizeof dummy;
    msg.msg_iov = &iov;
    msg.msg_iovlen = 1;
    msg.msg_control = buf;
    msg.msg_controllen = sizeof buf;
    ret = recvmsg(fds[1], &msg, 0);
    assert(ret != -1);
    cmsg = CMSG_FIRSTHDR(&msg);
    if (cmsg) {
      fdptr = (int *) CMSG_DATA(cmsg);
      memcpy(myfds, fdptr, (void *)cmsg + cmsg->cmsg_len - (void *)fdptr);
      printf("Child process received %d fds.\n", (int)(((void *)cmsg + cmsg->cmsg_len - (void *)fdptr) / sizeof(int)));
      close(fds[1]);
      for (i = 0; i < ((void *)cmsg + cmsg->cmsg_len - (void *)fdptr) / sizeof(int); i++) {
        close(myfds[i]);
      }
    } else {
      printf("Child process received 0 fds.\n");
      close(fds[1]);
    }
  } else {
    // parent process
    close(fds[1]);
    for (i = 0; i < NUM_FD; i++) {
      myfds[i] = socket(AF_INET, SOCK_STREAM, 0);
      assert(myfds[i] != -1);
    }
    iov.iov_base = dummy;
    iov.iov_len = sizeof dummy;
    msg.msg_iov = &iov;
    msg.msg_iovlen = 1;
    msg.msg_control = buf;
    msg.msg_controllen = sizeof buf;
    cmsg = CMSG_FIRSTHDR(&msg);
    cmsg->cmsg_level = SOL_SOCKET;
    cmsg->cmsg_type = SCM_RIGHTS;
    cmsg->cmsg_len = CMSG_LEN(sizeof(int) * NUM_FD);
    fdptr = (int *) CMSG_DATA(cmsg);
    memcpy(fdptr, myfds, NUM_FD * sizeof(int));
    msg.msg_controllen = cmsg->cmsg_len;
    ret = sendmsg(fds[0], &msg, 0);
    assert(ret != -1);
    printf("Parent process sent %d fds.\n", NUM_FD);
    close(fds[0]);
    for (i = 0; i < NUM_FD; i++) {
      close(myfds[i]);
    }
  }

  return 0;
}
```

**Comment by hujiajie** [comment]
Any feedback?

**Comment by pohly** [comment]
@jlaako can you work with the Joule kernel maintainers to get this included in the Ostro OS XT kernel?

**Comment by jlaako** [comment]
This is now in upstream linux-yocto/bxt-rebase, but there is a build failure (has been for some time) in i915 DRM driver, due to DRM driver backport issue, prevent me from updating the kernel update PR...

**Comment by hujiajie** [comment]
Thanks for the info. Do you know when the build failure will be fixed then, in a few days or weeks?

**Comment by jlaako** [comment]
Fix is now in: https://github.com/ostroproject/ostro-os-xt/pull/41

**Comment by hujiajie** [comment]
Glad to see the quick fix. I'll have a try soon.

**Comment by mythi** [comment]
@hujiajie please note it's not merged in master yet.

Edit: I mixed the PRs. It is there.
