### ISSUE TITLE
Jenkinsfile: XUnitPublisher marks status=FAIL, but GH status is set to SUCCESS

### ISSUE THREAD

**Issue by okartau** [ostroproject/ostro-os-xt#47]
In case of failure marked by XUnitPublisher step (limits exceeded),
CI pass still marks GH status as "OK".
Seems "catch (Exception e)" block is not executed if FAILURE marking
happens in class: XUnitPublisher code, i.e. in different thread.
Similar described in
http://jenkins-ci.361315.n4.nabble.com/Try-Catch-around-Failing-Plugin-td4836923.html

**Comment by okartau** [comment]
@kad

**Comment by mythi** [comment]
Fixed and released.
