### ISSUE TITLE
TPM not enabled in kernel

### ISSUE THREAD

**Issue by daweiwu** [ostroproject/ostro-os-xt#63]
Steps:
1. download source code here https://download.ostroproject.org/builds/ostro-os-xt/2016-10-21_02-32-06-build-190/ostro-os-xt_master-2016-10-21_02-32-06-build-190.tar.gz and extract it
2. $ cd  ostro-os-xt_master-2016-10-21_02-32-06-build-190 && source 
3. $ source ostro-init-build-env
4. $ bitbake -c menuconfig linux-yocto
5. $ Save kernel config , like /tmp/config
6. $ grep the config to find CONFIG_TCG_TPM=y and CONFIG_TCG_TIS=y
Expected results:
find tpm options in kernel config
Actual results:
tpm related options are not set

**Comment by mythi** [comment]
@jlaako these config entries are not explicitly set in security-tpm.cfg and they got disabled when we dropped IMA. Can you submit a PR in ostro-os-xt that adds these configs back?

**Comment by jlaako** [comment]
Fixed in https://github.com/ostroproject/meta-ostro-bsp/pull/66

**Comment by jlaako** [comment]
Also fixed in https://github.com/ostroproject/ostro-os-xt/pull/65

**Comment by mythi** [comment]
This is fixed.
