### ISSUE TITLE
Iotivity: Groupserver failed to create resource because of clientresponse error 33

### ISSUE THREAD

**Issue by yma11** [ostroproject/ostro-os-xt#67]
Build: 191
Steps:
1) On the target machine, start light server by command "/opt/iotivity/examples/resource/cpp/lightserver"
2) On the reference machine, with ostro/ostro-xt image inside, run group server by command "/opt/iotivity/examples/resource/cpp/groupserver", there will be error message showing:

root@intel-corei7-64:~# /opt/iotivity/examples/resource/cpp/groupserver
Usage: groupclient <0|1>
ConnectivityType: Default
ConnectivityType 0: IP
registerResource is called.

0 :: Quit 1 :: UNREGISTER RESOURCES

FOUND RESOURCE
        Resource URI : /a/light
        Resource Host : coap://[fe80::210:60ff:feb8:90e6]:57301
        Resource Interfaces : oic.if.baseline
        Resource Type : core.light
        resource registed!
0: listenCallback(): failed to create resource. clientResponse: 33

**Comment by mythi** [comment]
@yma11 Is this regression since 186? Are you using the meta-iotqa master test cases?

@testkit

**Comment by yma11** [comment]
@mythi this is a regression since 190. This problem doesn't happen in build 190 based on our test report https://otcqarpt.jf.intel.com/iot/iotos/tuchuck/full/2016-10-21_02-32-06-build-190. I am using the meta-iotqa master test cases, from test suites along with released build 191.

**Comment by mythi** [comment]
@yma11 Thanks. Have the test cases changed between 190 tests and now? 190-191 image delta is just the kernel.

**Comment by yma11** [comment]
@mythi Noop, our TC has no change. And I can see Iotivity has no change neither.

**Comment by yma11** [comment]
close this bug since the test scenario passed by maunal execution. This error doesn't affect functionality. Thanks.
