### ISSUE TITLE
pseudo xattr corruption

### ISSUE THREAD

**Issue by pohly** [ostroproject/ostro-os-xt#82]
https://bugzilla.yoctoproject.org/show_bug.cgi?id=10623 seems to change the length of the security.SMACK64TRANSMUTE value from 4 to 5, causing tar extraction errors when unpacking on the target system because Smack then checks the length.

Depending on the swupd client, the error gets ignored (leading to incorrect xattrs on the file and thus "swupd verify" failures) or prevents updating (seen for build 186).

**Comment by mythi** [comment]
PR merged.
